apiVersion: v1
kind: ConfigMap
metadata:
  name: sub-config
data:
  sub_config.conf: |
    <tars>
        <application>
            <client>
                stat=collector.tarsstat.StatObj@tcp -h xxx -p 4319
                property=collector.tarsproperty.PropertyObj@tcp -h xxx -p 4319
                modulename=X-BK-TOKEN:xxxx:TestApp.HelloGo
            </client>
        </application>
    </tars>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellogo
spec:
  selector:
    matchLabels:
      app: hellogo
  replicas: 1
  template:
    metadata:
      labels:
        app: hellogo
    spec:
      containers:
      - name: hellogo
        image: mirrors.tencent.com/crayon/hellogo:latest
        ports:
          - containerPort: 13000
        imagePullPolicy: Always
        readinessProbe:
            exec:
              command: ["tarscli", "hzcheck"]
            failureThreshold: 10
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
        lifecycle:
          preStop:
            exec:
              command: ["tarscli", "prestop"]
        volumeMounts:
          - name: config-volume
            mountPath: /tars/conf/sub_config.conf
            subPath: sub_config.conf
        env:
          - name: TARS_MERGE_CONF
            value: "/tars/conf/sub_config.conf"
      terminationGracePeriodSeconds: 90
      volumes:
        - name: config-volume
          configMap:
            name: sub-config
---
apiVersion: v1
kind: Service
metadata:
  name: hellogo-service
spec:
  type: NodePort
  selector:
    app: hellogo
  ports:
    - protocol: TCP
      port: 13000
      targetPort: 13000
      nodePort: 30001
