apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellogo
spec:
  selector:
    matchLabels:
      app: hellogo
  replicas: 1
  template:
    metadata:
      labels:
        app: hellogo
    spec:
      containers:
      - name: hellogo
        image: mirrors.tencent.com/crayon/hellogo:latest
        ports:
          - containerPort: 13000
        imagePullPolicy: Always
        readinessProbe:
            exec:
              command: ["tarscli", "hzcheck"]
            failureThreshold: 10
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
        lifecycle:
          preStop:
            exec:
              command: ["tarscli", "prestop"]
      terminationGracePeriodSeconds: 90
---
apiVersion: v1
kind: Service
metadata:
  name: hellogo-service
spec:
  type: NodePort
  selector:
    app: hellogo
  ports:
    - protocol: TCP
      port: 13000
      targetPort: 13000
      nodePort: 30001
